<a href="https://colab.research.google.com/github/naomori/codexa_LinearAlgebraIntroduction/blob/master/Chapter7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 行列の積の性質


#### 可換則
* 行列の積では、可換則は成立しない場合がある
* 行列のサイズも異なる場合がある

In [0]:
import numpy as np

In [0]:
a = np.array([[1,2], [3,4], [5,6]])
b = np.array([[5,6, 7], [7,8, 9]])

c = np.dot(a, b)
d = np.dot(b, a)

In [11]:
print(c)
print(c.shape)
print(d)
print(d.shape)

[[19 22 25]
 [43 50 57]
 [67 78 89]]
(3, 3)
[[ 58  76]
 [ 76 100]]
(2, 2)



#### 結合法則

* 結合法則は成り立つ

#### 単位行列

* A x I = I x A = A が成り立つとき、このIを単位行列という
* 対角線上に1が並ぶ

#### 逆行列

* $A * A^{-1} = A^{-1} * A = I$が成り立つとき、$A^{-1}$を逆行列という。
* エーインバースと呼ぶ

In [15]:
c = a.dot(b)
print(c)

[[19 22 25]
 [43 50 57]
 [67 78 89]]


In [16]:
d = b.dot(a)
print(d)

[[ 58  76]
 [ 76 100]]


## 単位行列を numpy で。

Numpy.eye を使います。

In [18]:
eye = np.eye(2)
print(eye)

[[1. 0.]
 [0. 1.]]


In [19]:
eye4 = np.eye(4)
print(eye4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
e = d.dot(eye)
print(e)

[[ 58.  76.]
 [ 76. 100.]]


In [22]:
f = np.linalg.inv(e)
print(f)

[[ 4.16666667 -3.16666667]
 [-3.16666667  2.41666667]]


In [23]:
print(e.dot(f))

[[ 1.00000000e+00 -5.32907052e-15]
 [-7.81597009e-14  1.00000000e+00]]
