<a href="https://colab.research.google.com/github/naomori/codexa_LinearAlgebraIntroduction/blob/master/Chapter6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 行列と行列の掛け算

In [0]:
import numpy as np

In [3]:
a = np.array([[1,3], [6,1], [2,0]])
b = np.array(([0,2], [11,7]))
c = np.dot(a, b)

print(a)
print(b)
print(c)

[[1 3]
 [6 1]
 [2 0]]
[[ 0  2]
 [11  7]]
[[33 23]
 [11 19]
 [ 0  4]]


In [5]:
d = np.array([[2,1,0], [9,6,2]])
e = np.array([[8,0,2], [1,3,1], [7,4,0]])
f = np.dot(d, e)

print(d)
print(d.shape)
print(e)
print(e.shape)
print(f)
print(f.shape)

[[2 1 0]
 [9 6 2]]
(2, 3)
[[8 0 2]
 [1 3 1]
 [7 4 0]]
(3, 3)
[[17  3  5]
 [92 26 24]]
(2, 3)


# 例題

身長から体重を求めてみる

| 名前 | 身長 |
|---|--|
|A| 180cm |
|B| 176cm|
|C|156cm|
|D|160cm|

1. $h_\theta(x) = 15 + 0.32x$
2. $h_\theta(x) = 8 + 0.43x$
3. $h_\theta(x) = -7 + 0.62x$

In [9]:
height = np.array([[1,180], [1,176], [1,156], [1,160]])
hx = np.array([[15, 8, -7], [0.32, 0.43, 0.62]])

weight = np.dot(height, hx)

print(height)
print(hx)
print(weight)

[[  1 180]
 [  1 176]
 [  1 156]
 [  1 160]]
[[15.    8.   -7.  ]
 [ 0.32  0.43  0.62]]
[[ 72.6   85.4  104.6 ]
 [ 71.32  83.68 102.12]
 [ 64.92  75.08  89.72]
 [ 66.2   76.8   92.2 ]]
