<a href="https://colab.research.google.com/github/naomori/codexa_LinearAlgebraIntroduction/blob/master/Chapter4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 行列の足し算

* 行数・列数が同じ場合：各要素を足すだけ
* 行数・列数が違う場合：計算できない

# 行列のスカラー倍（実数倍と思っておけば良い）

* 乗算：単純に各要素にかけるだけ。
* 割算：単純に各要素を割るだけ


In [0]:
import numpy as np
a = np.array([[2,4], [0,4], [7,9], [3,7]])
b = np.array([[9,2], [4,1], [1,7], [0,2]])

In [2]:
a + b

array([[11,  6],
       [ 4,  5],
       [ 8, 16],
       [ 3,  9]])

In [3]:
c = np.array([[1,3,7], [2,9,0]])
c + b

ValueError: ignored

In [4]:
6 * c

array([[ 6, 18, 42],
       [12, 54,  0]])

In [5]:
d = np.array([[6,3], [0,1]])
d / 3

array([[2.        , 1.        ],
       [0.        , 0.33333333]])

In [7]:
e = np.array([2,1,0,3])
f = np.array([4,2,3,1])
g = np.array([6,0,3,12])
(5*e) - f + (g/6)

array([ 7. ,  3. , -2.5, 16. ])