<a href="https://colab.research.google.com/github/naomori/codexa_LinearAlgebraIntroduction/blob/master/Chapter5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a = np.array([[2,5], [1,9], [0,3]])
b = np.array([[2], [3]])
c = np.dot(a, b)

In [14]:
print(a.shape)
print(b.shape)
print(c.shape)

(3, 2)
(2, 1)
(3, 1)


# 練習問題


In [0]:
x = np.array([[1,4], [2,0], [8,1], [3,5]])
y = np.array([[1], [3]])
z = np.dot(x, y)

In [16]:
print(x)
print(y)
print(z)

[[1 4]
 [2 0]
 [8 1]
 [3 5]]
[[1]
 [3]]
[[13]
 [ 2]
 [11]
 [18]]


# 例題

身長から体重を求めてみる

| 名前 | 身長 |
|---|--|
|A| 180cm |
|B| 176cm|
|C|156cm|
|D|160cm|

$h_\theta(x) = 15 + 0.32x$





In [17]:
height = np.array([[1,180], [1,176], [1,156], [1,160]])
hx = np.array([[15], [0.32]])

weight = np.dot(height, hx)

print(height)
print(hx)
print(weight)

[[  1 180]
 [  1 176]
 [  1 156]
 [  1 160]]
[[15.  ]
 [ 0.32]]
[[72.6 ]
 [71.32]
 [64.92]
 [66.2 ]]


バイアスの部分は 1 としてただ足し算になるような行列の形にしておく。