<a href="https://colab.research.google.com/github/naomori/codexa_LinearAlgebraIntroduction/blob/master/Chapter8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 逆行列と転置行列

* 逆行列：$A^{-1} × A = A^{-1} × A = I$
* 逆行列は正方行列でしか成立しない

In [0]:
import numpy as np

In [3]:
a = np.array([[1,2], [3,4]])
a1 = np.linalg.inv(a)

print(a)
print(a1)
print(a.dot(a1))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


#### 転置行列

* m行n列の行列Xと、行列Xの転置行列$X^T = Y$としたとき
* Yはn行m列の行列となり、要素は$Y_{ij} = X_{ji}$となる

In [4]:
X = np.array([[3,1], [2,6], [4,5]])
print(X)
print(X.T)

[[3 1]
 [2 6]
 [4 5]]
[[3 2 4]
 [1 6 5]]


In [5]:
print(X.shape)
print(X.T.shape)

(3, 2)
(2, 3)
