<a href="https://colab.research.google.com/github/naomori/codexa_LinearAlgebraIntroduction/blob/master/Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises

## Question.1

下記の行列Aと行列Bにおいて、行列の要素$A_{23}$および、$B_{14}$の正しい組み合わせを選びなさい。

$A = 
\begin{pmatrix}
3 & 1 & 8 \\
2 & 6 & 11 \\
4 & 5 & 0
\end{pmatrix}$

$B = 
\begin{pmatrix}
1 & 11 & 5 & 11 \\
3 & 1 & 2 & 6 \\
4 & 2 & 9 & 7 \\
5 & 8 & 4 & 1
\end{pmatrix}$


**C**: $A_{23} = 11$, $B_{14} = 11$

# Question.2

$\begin{pmatrix}
1 & 3 \\
7 & 1
\end{pmatrix} + 
\begin{pmatrix}
2 & 1 \\
5 & 6
\end{pmatrix} +
\begin{pmatrix}
4 & 2 \\
6 & 10
\end{pmatrix} \div 2$

In [2]:
import numpy as np
a = np.array([[1,3], [7,1]])
b = np.array([[2,1], [5,6]])
c = np.array([[4,2], [6,10]])
d = a + b - c/2
print(d)

[[1. 3.]
 [9. 2.]]


**C**: $\begin{pmatrix}
1 & 3 \\
9 & 2
\end{pmatrix}$

## Question.3

$\begin{pmatrix}
2 & 5 & 7 \\
1 & 3 & 2
\end{pmatrix} \times
\begin{pmatrix}
2 & 3 \\
1 & 5 \\
8 & 4
\end{pmatrix}$

In [3]:
a = np.array([[2,5,7], [1,3,2]])
b = np.array([[2,3], [1,5], [8,4]])
print(a.dot(b))

[[65 59]
 [21 26]]


**D**: $\begin{pmatrix}
65 & 59 \\
21 & 26
\end{pmatrix}$

## Question.4

$A =
\begin{pmatrix}\
1 & 2 \\
3 & 4
\end{pmatrix}$
$B =
\begin{pmatrix}
5 & 6\\
7 & 8
\end{pmatrix}$
$C =
\begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix}$

In [4]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.eye(2)
print(a)
print(b)
print(c)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1. 0.]
 [0. 1.]]


In [5]:
# A
print(a.dot(b))
print(b.dot(a))

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [6]:
# B
d = a.dot(b)
f = b.dot(c)
print(d.dot(c))
print(a.dot(f))


[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


**A**が正しくない

## Question.5

$A =
\begin{pmatrix}
1 & 5 & 2 \\
6 & 3 & 9 \\
2 & 7 & 1
\end{pmatrix}$

In [7]:
a = np.array([[1,5,2],[6,3,9],[2,7,1]])
print(a)
ai = np.linalg.inv(a)
print(ai)

[[1 5 2]
 [6 3 9]
 [2 7 1]]
[[-0.83333333  0.125       0.54166667]
 [ 0.16666667 -0.04166667  0.04166667]
 [ 0.5         0.04166667 -0.375     ]]


In [8]:
print(a.T)

[[1 6 2]
 [5 3 7]
 [2 9 1]]


**A**が正解